server:
  port: 8081
spring:
  flyway:
    enabled: true
    locations: classpath:db/migration
  application:
    name: forumapi
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/forum
    username: dev
    password: dev

